language: java

sudo: required

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - sudo service docker restart ; sleep 10
  
install:
  - docker run -d -p 127.0.0.1:27017:27017 mongo:3
  - mvn install -DskipTests=true

script:
  - mvn test
