language: java

env:
  - secure: "hSxCwjimhCBNugua4DyIdpLW9+KKaIAH13H5D9EKRjyN7ejKEwh+ASXE5572UdpPsotZNUraZrPHsBJ95t1pPA8bqvQxRXH5MvfbiaB5Wg/XCeEHroEf7a+Vh9WUD4bPjxv1hsMU6kCPZU9MduzLDTZ16Mw3dUUq7pTG86FsiD+PlVfu0UnPWek9iqkVtcBMgDq4q+lRcphkE8sVri/zOfCOGpQy66CdSTQNCv75uw96GgJ8WJuV93zZ8klhMbIee7PAhDxacbM14zI4EJfQxpQjCKdnUBl4AxQ0YYcxG1x2h6eZbTTqpQPUzNbXBdw01nyQLiXR1niQ7en4HgyJfYRDoqhTZZ6O/rfuFs+FN//XI9BfzDPsNA6N81NPvtdiZWuJE52EncX4EO+OBRoSK2Q2RfFIsT/3quAmog0hLD++UUcs0BDJtaxeqlWneET0rIcAMcBvWECNP9AMmSDJgFLyRv9uOHAOL1zCkl3FFdUu1Zx/yenNnc4Kqvnd9XUqiFdfra83YjkQstB9tFjLlhar5PLK3MGUeDPgmIuQ4Pbc9JkLAzRq9Tns+agX3hsPtYf3jJ/u/lcyhD3uEjS7hNkLOa99irV5hkRARqW913S4ZvPyvLfWeCcd4hkH23eiMSvOolhrYXJqeb2Mo+yU8MGN4BJxLZATz3Uurn6HLoU="
  - secure: "QCcFgHJVCCbpGPfsAPZgzfnRyHGCnGFsHdFK/Gtqhs1thnlb1uaD6DyxdVAlD+Jj0/QIKprZONDdmZtfIdpLrk8vt+whRkq5diNyofCHsnXCVupC3aDWpfuTe9sL6Oz0sUxLwn27DSIrAmHFTCdOx4BAPsd8ph/b7jmTQ4Eh3kWOrZZHjxbQBbb0voMX4E1PgSutzLvrEVnNCzz2xaakrYU2NaYMTy9NBwfiZiH/SK//Oy2FWScKbHhQvoJTqbFzKIGcvTfeW/9OVwlSjs5XiuE2Bdx7aBijUK4PJX9HXOqFYWKjOzqLqUZeIegyKTBH1G6o9Fx8ePyXqoWm7ChREIRSyyYbYcSZYMiRqi8G4nc5iUpr6hr+9VGyJjQbPifvtYDG+sYKR4YkhKAqZZgftdRwE522QfXDIQk9Jb8sDjZJRnbG+7rFMWN8hxVjFEZLMkp3GRa6n4z/1YhowgPGXMgzqeEhdcjqmUSiY7BuyoKoBo28yr2kNbGzk1aIRidw12IQVoqLL4A8Os4bS/mf5lsI6RONP/3PcsoaLCadgmXCW8BfmgjETWDj/E1M9rROg+HbxoHAbrN7F0J0tqUEzMbvrBWpVqU17r9ZheJ9QF8qeVrUIrfmkwAbFj2ZUBPzwsYBqdyAqod+1rjyM6hMFRZqmxoOFz0c+kD64AUuGP4="
  - secure: "lAW30dZQ8zjPbUT88Ehhs9noY/LgzHmzcaehEFP1aOhvuGfNtqnind44UTIlGvF9MOK04hz3/GZTtgf3MRin0w7f49fQZj2wIO6zfQzZ8eXQjqYTc35WH6GueWhf/UdRcZEEt6KJAz8bP8xkrdIjp21cxY2bY+HEG+kOajzXKZGCKe3MlrjfF39hfEikq6IyGe063b4ORZu5T/DD6zffNDuvcPj36xjgyginO2KPCIfOUB0jd6zxiQEP/ob/lTGNIbUpoOMOTckxz1lNFfWHjpoeC8YuXwogeGi7Tfn1dJUE70N/kX2ufJ9ln9knsgOEvwqHvcG9pVeFGBe+DsRj2ezO3LJQpnW+M9ulObpbAhrjuPkMT3WiSh1HXTr4XDUxvgbvGGbV2U85hG+qsbtDH9BqURnZ07mDQooE3X7RYZlDHGTeLAtJMWypYC0VwWUxQLwtcTL9tYcGdjEzIaYiDvXyr3D6/PO+UjkbbyNUmRW2CuAwm+ArpoLbzuVMl8v+uPTCPs8iTP79FF9gWJZOGlGjYGle/95d5XBSApRXoapwQAcB/qeSEJQkV41paKlQDmBrf3n9NHNmXU9orY6XJObloiYemYE+UCOS8p2Rkx/A9F93Wg90ECHQA7aFLzg2DrJNKPuZ3uqR+fNyirdSU1vw1ykCNvKD1o115Jkxf28="

jdk:
  - oraclejdk8

services:
  - mongodb
  - docker

install:
  mvn install -DskipTests=true

script:
  mvn test

before_install:
  docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  docker build -t authomator/authomator-spring-api .
  docker push
